### PR TITLE
CORGI-790: Tweak links for provides, sources, and upstreams

### PR DESCRIPTION
**Pull request by juspence**
@RedHatProductSecurity/corgi-devs Please review this change thoroughly. This is our last chance to make changes here before our next release, and I really don't want to go back to OpenLCS and tell them we're changing things for a third time.

If this looks OK, I'll deploy this to stage and confirm we still don't have any "Bad Gateway" errors, then merge this.

### CODE REVIEW

**Comment by jasinner** [comment]
I tried this out in Dev but clicking through the links on the Web UI returns no results for me, eg:

[sources=pkg:golang/github.com/hashicorp/aws-cloudformation-resource-schema-sdk-go@v0.18.0](http://localhost:8080/api/v1/components?sources=pkg:golang/github.com/hashicorp/aws-cloudformation-resource-schema-sdk-go@v0.18.0)

@JimFuller-RedHat Is that the format of the URL you were expecting?

The same request for the old style links returns 1000+ results:

`https://{CORGI_DOMAIN}/api/v1/components/b558b38d-273d-48a9-a6f6-a5d479a37947/sources`

**Comment by JimFuller-RedHat** [comment]
I think this is reversed eg. to find sources your would use ?provides and if u want provides use ?sources

**Comment by jasinner** [comment]
Yes, you are correct, this returned the results I was expecting:

'api/v1/components?provides=pkg:golang/github.com/hashicorp/aws-cloudformation-resource-schema-sdk-go@v0.18.0'

**Review by jasinner — APPROVED** [review]
LGTM, just need to swtich provides/sources and upstreams/downstreams.

**Comment by juspence** [comment]
It's not backwards, it's just really confusing. You can look at the tests or the header comments on the new methods for an explanation of the logic.

Basically, the "provides" field shows all the **provided** components of this component. It's expected that a Golang component will not have any provides of its own.

The ?provides= filter is different, and shows all the **source** components which have this component in their list of provided components (have this component in their "provides" field).

The ?provides= filter is therefore the same as the "sources" field. The "sources" field shows all the **source** components of this component, so the Golang example above should have at least 1 result, like a source RPM, RPM module, or container.

The ?sources= filter only shows all the **provided** components which have this component in their list of source components (have this component in their "sources" field).

Upstreams and downstreams follow the same logic.

**Comment by jasinner** [comment]
Ah you are right. The links are correct! Sorry for the confusion.

**Comment by juspence** [comment]
No problem, thanks for reviewing!

**Pull request merged**
