### PR TITLE
CORGI-652 reverse proxy via nginx

### PR DESCRIPTION
**Pull request by jasinner**
Yet another iteration of the file truncation issue solution. I finally decided to give up on serving static files via gunicorn in favour of NGinx. In this iteration using NGinx as a reverse proxy.

Not that to use NGinx as a reverse proxy in dev you'll need to update the url you access Corgi on from port 8008 to 8080

### CODE REVIEW

**Comment by JimFuller-RedHat** [comment]
LGTM

**Comment by jasinner** [comment]
I updated this a bit to use the origin ALLOWED_HOSTS config for stage and prod.

I also simplified the nginx config in dev.

**Comment by JimFuller-RedHat** [comment]
LGTM

**Comment by mprpic** [comment]
If we have NGINX serving this content, we don't need whitenoise at all. The manifest generation can just place the files in some director that NGINX is serving it out of and that's it. The path to the files can also then be something more standard like `/files/sbom/<file>`.

**Pull request merged**
