### PR TITLE
CORGI-501 latest filter uses python

### PR DESCRIPTION
**Pull request by jasinner**
This uses Python's version_utils library to compare root component versions. I searched the data and found that if you restrict the component search by ROOT_COMPONENT, ProductStream, and name you get at most 100 components (for example kernel in rhel-7.7). Therefore sorting in Python should not be much slower than sorting in the DB.

Leaving in draft until I've tested the reconciliation report.

### CODE REVIEW

**Comment by jasinner** [comment]
@JimFuller-RedHat  please review

**Comment by JimFuller-RedHat** [comment]
LGTM though we should proceed carefully

**Comment by jasinner** [comment]
Using a DB backup taken on Monday, I get 99% coverage from deptopia-reconcilation for rhel-7.9.0.z using this branch, whereas it's 17% on stage.

**Comment by jasinner** [comment]
Attached a full reconciliation report to CORGI-501 run against this branch in dev. It's using data that's at least a week old, but the rhel cover is much better:

```
2023-03-03 17:02:00,561 [INFO] o:redhat:rhel-6-els: coverage: 45%
2023-03-03 17:07:10,484 [INFO] o:redhat:rhel:7.4.z coverage: 100%
2023-03-03 17:09:49,228 [INFO] o:redhat:rhel:7.6.z coverage: 100%
2023-03-03 17:12:32,621 [INFO] o:redhat:rhel:7.7.z coverage: 100%
2023-03-03 17:18:18,970 [INFO] o:redhat:rhel:7.9.z coverage: 99%
2023-03-03 17:20:24,175 [INFO] o:redhat:rhel:8.1.0.z coverage: 87%
2023-03-03 17:22:32,956 [INFO] o:redhat:rhel:8.2.0.z coverage: 86%
2023-03-03 17:24:47,153 [INFO] o:redhat:rhel:8.4.0.z coverage: 78%
2023-03-03 17:27:04,670 [INFO] o:redhat:rhel:8.6.0.z coverage: 75%
2023-03-03 17:29:23,482 [INFO] o:redhat:rhel:8.7.0.z coverage: 65%
2023-03-03 17:31:36,915 [INFO] o:redhat:rhel:8.8.0 coverage: 70%
2023-03-03 17:33:32,114 [INFO] o:redhat:rhel:9.0.0.z coverage: 99%
2023-03-03 17:36:32,081 [INFO] o:redhat:rhel:9.1.0.z coverage: 87%
2023-03-03 17:38:30,181 [INFO] o:redhat:rhel:9.2.0 coverage: 88%

```
Compared with this from stage:
```
2023-03-02 11:36:12,211 [INFO] o:redhat:rhel-6-els: coverage: 33%
2023-03-02 11:36:30,511 [INFO] o:redhat:rhel:7.4.z coverage: 95%
2023-03-02 11:37:15,684 [INFO] o:redhat:rhel:7.6.z coverage: 94%
2023-03-02 11:37:44,023 [INFO] o:redhat:rhel:7.7.z coverage: 15%
2023-03-02 11:38:18,069 [INFO] o:redhat:rhel:7.9.z coverage: 17%
2023-03-02 11:38:31,473 [INFO] o:redhat:rhel:8.1.0.z coverage: 77%
2023-03-02 11:38:47,613 [INFO] o:redhat:rhel:8.2.0.z coverage: 75%
2023-03-02 11:39:09,644 [INFO] o:redhat:rhel:8.4.0.z coverage: 75%
2023-03-02 11:39:36,469 [INFO] o:redhat:rhel:8.6.0.z coverage: 70%
2023-03-02 11:40:05,947 [INFO] o:redhat:rhel:8.7.0.z coverage: 63%
2023-03-02 11:40:15,403 [INFO] o:redhat:rhel:8.8.0 coverage: 70%
```

Looking over the other product streams I don't see any which have lower coverage.

**Pull request merged**
